### ISSUE TITLE
Ideation for v2

### ISSUE THREAD

**Issue by jsonkao** [jsonkao/jasonkao.me#8]
# Ideas for v2 of `jasonkao.me`

- **Blog:** finally starting that blog. It could start with a profile of the people I've been talking to (themes could include my journey, exploring data journalism, exploring tech policy, exploring computer science, undergrad venturing).
- **Site structure:** If I want a blog, then the site can't be a SPA anymore.
- **Homepage layout:** why force people to hover over text before they can see your projects? Have them laid out in a grid, save the current `SelectedProjects` feature for open source or more minor things. (Or maybe just have them all out, like that NPR blog post or Sarah-something from 538.
- **Banner/snackbar on top:** available for freelance hire

**Comment by NicholasLYang** [comment]
Wow using GitHub issues how pretentious.

Blog - I'd keep this simple. Use something like Hugo, Gatsby, etc.

Site structure - You could just have routes go to a non React location. You'd have to run your own server but that's not hard. Or just keep your blog on a separate domain. blog.jasonkao.me?

HomePage layout - I like your current layout, but I'm open to new ideas. Grids are cool.

Banner - A little unsubtle. Maybe just an additional line of text with a different color?

**Comment by jsonkao** [comment]
Good ways to curate interactives work:
- https://graphics.wsj.com/
- https://www.bloomberg.com/graphics

**Comment by jsonkao** [comment]
Logo icons (colored, not #333'd SVG) for social media/contact links

**Comment by jsonkao** [comment]
Clips should be reduced to that initial visible-on-hover layout from v1.

**Comment by jsonkao** [comment]
For a more graphics/journalism-oriented layout, check out http://www.alizaaufrichtig.com.

**Comment by jsonkao** [comment]
Leave Greedux.

**Comment by NicholasLYang** [comment]
Word. My site doesn't compile anymore so I'm gonna port to create react app

**Comment by jsonkao** [comment]
Being open in your intro: https://thomasoide.github.io

**Comment by jsonkao** [comment]
Pretty clean: http://stuartathompson.com

**Comment by jsonkao** [comment]
Honestly the dream: http://www.emilykassie.com

**Comment by jsonkao** [comment]
This is kinda tight: https://www.swyx.io

**Comment by jsonkao** [comment]
http://deniselu.com. Low quality gifs are okay. Layout is clean.

**Comment by jsonkao** [comment]
The centered nutgraf leading into grid I'm starting to like. It just feels less much http://priyakrishnakumar.com/

**Comment by jsonkao** [comment]
https://jackielgu.github.io

**Comment by jsonkao** [comment]
https://tracyma.com/

**Comment by jsonkao** [comment]
http://www.charliesmart.info/

**Comment by jsonkao** [comment]
https://jeremycflin.github.io/

**Comment by jsonkao** [comment]
https://lisacharlotterost.de/

**Comment by jsonkao** [comment]
Migrating this issue to a newer one to aggregate/cut some ideas
